services:
  # 1. Backend (API)
  - type: web
    name: focuspath-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: dev

  # 2. Frontend (Static Site)
  - type: web
    name: focuspath-web
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      # Це важливо для React/Vue додатків (SPA роутинг)
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      # Автоматично бере URL бекенду (напр. https://focuspath-api.onrender.com)
      - key: VITE_API_URL
        fromService:
          type: web
          name: focuspath-api
          envVarKey: RENDER_EXTERNAL_URL
