import dotenv from 'dotenv';
import path from 'path';

import mongoose from 'mongoose';
import { connectDB } from '@config/db';
import Habit from '@models/Habit';
import Plan from '@models/Plan';
import User from '@models/User';
import type { HabitType, PlanCategory } from '@shared/index';
import { buildSchedule } from '@services/habitSchedule';
import { generateHabitPlan } from '@services/openAiService';
import { MODERATION_MODEL, reviewPlan } from '@services/moderationService';
import { scheduleHash } from '@services/planContent';
import { startOfUtcDay } from '@utils/dates';
import { logger } from '@config/logger';

/**
 * The library's cold start.
 *
 * A template library with nothing in it is a template library nobody takes
 * anything from, and by design the first user-published plan is a day-zero plan
 * — published at peak motivation, before its author has walked any of it. These
 * are generated by the project's own AI and meant to be read through by hand
 * before anyone else sees them.
 *
 * They carry the `official` badge, which is deliberately *not* the `proven` one:
 * one says the project stands behind it, the other says a person finished it.
 * Merging them would be dishonest in both directions.
 *
 * Useful side effect: this is the first real content the moderation gate ever
 * sees, well before a live user reaches it.
 */

interface SeedDefinition {
    title: string;
    description: string;
    category: PlanCategory;
    type: HabitType;
    duration: number;
    color: string;
    icon: string;
}

/** Colour and icon values are the ones the pickers actually emit. */
const SEEDS: readonly SeedDefinition[] = [
    { title: 'Walk 30 minutes a day', description: 'A daily walk, built up from a short first outing.', category: 'fitness', type: 'build', duration: 30, color: 'green', icon: 'footprints' },
    { title: 'Couch to 5K', description: 'From standing start to five kilometres, one run at a time.', category: 'fitness', type: 'build', duration: 60, color: 'orange', icon: 'person running' },
    { title: 'Strength training three times a week', description: 'A progressive routine you can run at home or in a gym.', category: 'fitness', type: 'build', duration: 45, color: 'red', icon: 'person lifting weights' },
    { title: 'Daily stretching routine', description: 'Ten minutes of mobility work, every day.', category: 'fitness', type: 'build', duration: 30, color: 'teal', icon: 'person in lotus position' },
    { title: 'Drink enough water', description: 'Build the habit of drinking water through the day.', category: 'health', type: 'build', duration: 21, color: 'lightblue', icon: 'droplet' },
    { title: 'Quit smoking', description: 'A gradual reduction plan with replacements for the hard moments.', category: 'health', type: 'quit', duration: 90, color: 'red', icon: 'fire' },
    { title: 'Cut down on alcohol', description: 'Fewer drinking days each week, with something to do instead.', category: 'health', type: 'quit', duration: 60, color: 'purple', icon: 'droplet' },
    { title: 'Take the stairs', description: 'Small movement built into a day that has none.', category: 'health', type: 'build', duration: 21, color: 'green', icon: 'footprints' },
    { title: 'Daily meditation', description: 'From two minutes to twenty, without forcing it.', category: 'mind', type: 'build', duration: 30, color: 'purple', icon: 'person in lotus position' },
    { title: 'Keep a gratitude journal', description: 'Three lines a night about the day you actually had.', category: 'mind', type: 'build', duration: 30, color: 'yellow', icon: 'pencil' },
    { title: 'Morning pages', description: 'Write before the day starts talking back.', category: 'creativity', type: 'build', duration: 30, color: 'white', icon: 'pencil' },
    { title: 'Learn Spanish basics', description: 'Enough Spanish to hold a first conversation.', category: 'learning', type: 'build', duration: 60, color: 'orange', icon: 'notebook' },
    { title: 'Read every day', description: 'Twenty pages a day, whatever the book.', category: 'learning', type: 'build', duration: 30, color: 'blue', icon: 'books' },
    { title: 'Learn to touch type', description: 'From hunting for keys to typing without looking.', category: 'learning', type: 'build', duration: 45, color: 'blue', icon: 'laptop' },
    { title: 'Practise an instrument', description: 'Fifteen focused minutes a day beats an hour on Sunday.', category: 'creativity', type: 'build', duration: 60, color: 'purple', icon: 'musical note' },
    { title: 'Draw something daily', description: 'A sketchbook habit that survives being bad at it.', category: 'creativity', type: 'build', duration: 30, color: 'yellow', icon: 'pencil' },
    { title: 'Plan tomorrow tonight', description: 'Five minutes at night that decide the next morning.', category: 'productivity', type: 'build', duration: 21, color: 'white', icon: 'notebook' },
    { title: 'Deep work block every morning', description: 'One protected hour before the day fills up.', category: 'productivity', type: 'build', duration: 30, color: 'blue', icon: 'alarm clock' },
    { title: 'Inbox to zero', description: 'Get on top of email and stay there.', category: 'productivity', type: 'build', duration: 21, color: 'lightblue', icon: 'check mark' },
    { title: 'No phone for the first hour', description: 'Start the day in your own head, not someone else’s.', category: 'digital', type: 'quit', duration: 30, color: 'white', icon: 'alarm clock' },
    { title: 'Cut social media to 30 minutes', description: 'Reclaim the hours that vanish without being spent.', category: 'digital', type: 'quit', duration: 30, color: 'purple', icon: 'alarm clock' },
    { title: 'A consistent bedtime', description: 'The same lights-out time, defended for a month.', category: 'sleep', type: 'build', duration: 30, color: 'blue', icon: 'crescent moon' },
    { title: 'No screens before bed', description: 'An hour of wind-down that is not a screen.', category: 'sleep', type: 'quit', duration: 21, color: 'purple', icon: 'bed' },
    { title: 'Cook at home', description: 'Five home-cooked dinners a week, planned and shopped for.', category: 'nutrition', type: 'build', duration: 30, color: 'green', icon: 'cooking' },
    { title: 'Eat vegetables at every meal', description: 'A simple rule, applied to meals you already eat.', category: 'nutrition', type: 'build', duration: 21, color: 'green', icon: 'broccoli' },
    { title: 'Cut out added sugar', description: 'Wean off the sweet default, one category at a time.', category: 'nutrition', type: 'quit', duration: 45, color: 'red', icon: 'red apple' },
    { title: 'Track every expense', description: 'A month of knowing exactly where the money goes.', category: 'money', type: 'build', duration: 30, color: 'yellow', icon: 'money bag' },
    { title: 'A no-spend month', description: 'Essentials only, for thirty days.', category: 'money', type: 'quit', duration: 30, color: 'teal', icon: 'shopping bags' },
    { title: 'Message someone you miss', description: 'Rebuild the friendships that went quiet.', category: 'social', type: 'build', duration: 21, color: 'red', icon: 'red heart' },
    { title: 'Tidy for ten minutes', description: 'A home that never gets far enough away to dread.', category: 'other', type: 'build', duration: 21, color: 'lightblue', icon: 'broom' },
];

export interface SeedReport {
    created: number;
    skipped: number;
    rejected: number;
}

/**
 * Creates any official plan that is not already there, and leaves the rest
 * alone — so an interrupted run can simply be repeated.
 *
 * Each seed becomes a real habit on the official account first, because a plan
 * is a snapshot *of a habit*: giving them a source keeps one path through the
 * code instead of a second one that exists only for seeding.
 *
 * Expects an open connection; the CLI below owns connecting.
 */
export const seedOfficialPlans = async (authorId: mongoose.Types.ObjectId): Promise<SeedReport> => {
    const report: SeedReport = { created: 0, skipped: 0, rejected: 0 };

    for (const seed of SEEDS) {
        const existing = await Plan.findOne({ title: seed.title, official: true });
        if (existing) {
            report.skipped += 1;
            continue;
        }

        const generated = await generateHabitPlan(seed.title, seed.type, seed.duration);
        const dayTitles = Array.from(
            { length: seed.duration },
            (_unused, index) => generated.dailyTasks[index]?.dayTitle ?? seed.title,
        );

        const review = await reviewPlan({
            title: seed.title,
            description: seed.description,
            dayTitles,
        });

        if (review.verdict === 'reject') {
            logger.warn({ title: seed.title, reason: review.reason }, 'Seed plan rejected by moderation');
            report.rejected += 1;
            continue;
        }

        const startDate = startOfUtcDay(new Date());
        const habit = await Habit.create({
            title: seed.title,
            description: seed.description,
            category: seed.category,
            startDate,
            duration: seed.duration,
            type: seed.type,
            color: seed.color,
            icon: seed.icon,
            userId: authorId,
            currentStreak: 0,
            isCompleted: false,
            dailyCompletions: buildSchedule(startDate, seed.duration, seed.title).map((day, index) => ({
                ...day,
                dayTitle: dayTitles[index],
            })),
        });

        const plan = await Plan.create({
            title: seed.title,
            description: seed.description,
            category: seed.category,
            language: review.language,
            type: seed.type,
            duration: seed.duration,
            color: seed.color,
            icon: seed.icon,
            days: dayTitles.map(dayTitle => ({ dayTitle })),
            author: { userId: authorId },
            sourceHabitId: habit._id,
            contentHash: scheduleHash(seed.duration, dayTitles),
            official: true,
            moderation: {
                checkedAt: new Date(),
                model: MODERATION_MODEL,
                verdict: review.verdict,
                reason: review.reason,
            },
        });

        habit.publishedPlanId = plan._id as mongoose.Types.ObjectId;
        await habit.save();

        report.created += 1;
        logger.info({ title: seed.title, language: review.language }, 'Seeded official plan');
    }

    return report;
};

const run = async () => {
    dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

    const email = process.env.ADMIN_EMAIL;
    if (!email) {
        logger.error('ADMIN_EMAIL must be set in .env — official plans are published under that account');
        process.exit(1);
    }

    await connectDB();

    const author = await User.findOne({ email });
    if (!author) {
        logger.error(`No account for ${email}. Run "npm run seed:admin" first.`);
        await mongoose.disconnect();
        process.exit(1);
    }

    const report = await seedOfficialPlans(author._id as mongoose.Types.ObjectId);
    logger.info(report, 'Official plan seeding complete');

    await mongoose.disconnect();
};

if (require.main === module) {
    run().catch(async (error) => {
        logger.fatal({ err: error }, 'Failed to seed official plans');
        await mongoose.disconnect().catch(() => undefined);
        process.exit(1);
    });
}
